version: '3'
services:

  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: payroll
      
    ports:
      - "3306:3306"
    volumes:
      - database_mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/payroll
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8088:8080"
    networks:
      - mynetwork

volumes:
  database_mysql-data:
    external: true

networks:
  mynetwork:
    driver: bridge

